### ISSUE TITLE
Making a decision does not affect score

### ISSUE THREAD

**Issue by mjmeli** [mjmeli/whodecidesfood-api#4]
Making a decision does not currently affect score.

1. Develop an algorithm for change (i.e. 1 point per decision)
2. Ensure score increase when new decision is made
3. Ensure score decrease when decision is deleted
4. Ensure score adjustments when decision participant is updated

Any comments?

**Comment by kgeller** [comment]
Agreed, those are the only four cases I can see right now.

**Comment by mjmeli** [comment]
Resolved, with limited testing. Should add integration tests later.
